#!/usr/bin/env bash

while true; do
#auto-restart until ctrl-c or exit 0

git pull
./gradlew -Dorg.gradle.daemon=false dist
java -jar build/libs/CoreBot.jar

excode=$?
if [ $excode -eq 0 ] || [ $excode -eq 130 ]; then
  exit 0
fi
done